version: '3.4'
services:
  svelte:
    restart: always
    build:
      context: ./frontend
      dockerfile: ../docker/production/svelte/Dockerfile
      args:
        - VITE_API_DOMAIN=https://api.unnwhiteboard.com
    ports:
      - 3000:3000
    environment:
      - VITE_API_DOMAIN=https://api.unnwhiteboard.com
    depends_on:
      - mongo
  mongo:
    image: mongo
    expose:
      - 27017
    volumes:
      - mongodb:/data/db
  node:
    restart: always
    build:
      context: ./crawler
      dockerfile: ../docker/production/node/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./crawler:/app
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017
      - NODE_CONFIG_DIR=/app/src/config
    depends_on:
      - mongo

    
volumes:
 mongodb: