version: '3'
services:
  node:
    restart: always
    build: 
      context: .
      dockerfile: ./docker/local/node/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  redis:
    image: redis:latest
    restart: on-failure
volumes:
 mongodb: