export default {
    "dev": "🤓Developer (18,063)",
    "engineer": "🤓Engineer (13,874)",
    "senior": "👵Senior (7,947)",
    "exec": "💼Executive (5,714)",
    "javascript": "☕️JavaScript (5,058)",
    "ruby": "💎Ruby (3,972)",
    "full stack": "🥞Full Stack (3,182)",
    "devops": "♾️DevOps (2,966)",
    "front end": "🎨Front End (2,857)",
    "backend": "🍑Backend (2,262)",
    "php": "🐘PHP (2,116)",
    "non tech": "🔌Non Tech (2,105)",
    "web dev": "🤓Web Developer (2,057)",
    "ios": "🍎iOS (2,034)",
    "marketing": "🚥Marketing (1,914)",
    "design": "🎨Design (1,898)",
    "c": "🔷C (1,619)",
    "react": "⚛️React (1,521)",
    "node": "🔗Node (1,389)",
    "mobile": "📱Mobile (1,248)",
    "admin": "♾️Admin (1,242)",
    "java": "☕️Java (1,213)",
    "golang": "🐀Golang (1,112)",
    "python": "🐍Python (1,054)",
    "sales": "💼Sales (1,033)",
    "product manager": "📦Product Manager (1,009)",
    "architecture": "📦Architecture (949)",
    "customer support": "🎧Customer Support (937)",
    "android": "🤖Android (854)",
    "css": "🎨CSS (819)",
    "sys admin": "♾️Sys Admin (813)",
    "c plus plus": "➕C Plus Plus (777)",
    "meteor": "☄️Meteor (773)",
    "html": "🔡HTML (765)",
    "user interface": "🎨User Interface (764)",
    "user experience": "🎨User Experience (753)",
    "js": "☕️JavaScript (688)",
    "cloud": "☁️Cloud (679)",
    "quality assurance": "🔬Quality Assurance (636)",
    "infosec": "🔑InfoSec (585)",
    "full time": "⏰Full Time (535)",
    "angular": "🅰️Angular (516)",
    "testing": "🧪Testing (507)",
    "api": "🤖API (410)",
    "data science": "👩‍🔬Data Science (397)",
    "teaching": "👨‍🏫Teaching (382)",
    "ops": "♾️Ops (378)",
    "sql": "🐬SQL (377)",
    "finance": "💰Finance (376)",
    "wordpress": "✍️Wordpress (368)",
    "analyst": "🤔Analyst (361)",
    "saas": "📦SaaS (350)",
    "education": "👨‍🏫Education (344)",
    "junior": "👶Junior (306)",
    "linux": "🐧Linux (304)",
    "drupal": "💧Drupal (294)",
    "consulting": "💼Consulting (267)",
    "react native": "⚛️React Native (266)",
    "internship": "Internship (265)",
    "aws": "☁️AWS (263)",
    "medical": "🚑Medical (253)",
    "social media": "✍️Social Media (253)",
    "bus dev": "🤓Bus Developer (248)",
    "ecommerce": "🛍Ecommerce (240)",
    "scala": "☕️Scala (235)",
    "jquery": "🧩jQuery (224)",
    "game dev": "🕹Game Developer (211)",
    "machine learning": "🤖Machine Learning (185)",
    "typescript": "🟦Typescript (183)",
    "copywriting": "✍️Copywriting (182)",
    "ads": "📗Ads (181)",
    "stats": "👩‍🔬Stats (181)",
    "seo": "🔎SEO (179)",
    "excel": "📗Excel (172)",
    "rails": "🛤Rails (168)",
    "part time": "⏰Part Time (158)",
    "docker": "🐳Docker (152)",
    "mongo": "🍃Mongo (147)",
    "tech lead": "👩‍✈️Tech Lead (147)",
    "mongodb": "🍃Mongo (142)",
    "web3": "💎Web3 (133)",
    "postgres": "🐬Postgres (132)",
    "dot net": "🌊Dot Net (131)",
    "vue": "💚Vue (128)",
    "swift": "🐇Swift (119)",
    "graphql": "⚛️GraphQL (119)",
    "salesforce": "☁️Salesforce (118)",
    "laravel": "📦Laravel (115)",
    "big data": "🧠Big Data (112)",
    "kubernetes": "🦑Kubernetes (104)",
    "elasticsearch": "🧩Elasticsearch (102)",
    "frontend": "🎨Frontend (99)",
    "dba": "🥞Database Admin (94)",
    "virtual assistant": "Virtual Assistant (93)",
    "video": "Video (91)",
    "blockchain": "⛓Blockchain (91)",
    "recruiter": "🎯Recruiter (90)",
    "developer": "🤓Developer (82)",
    "mysql": "🐬MySQL (79)",
    "qa": "🕵️Quality Assurance (75)",
    "product": "📦Product (74)",
    "crypto": "🏅Crypto (73)",
    "git": "📦Git (73)",
    "ux": "🎨UX (68)",
    "startup": "🚀Startup (66)",
    "embedded": "💡Embedded (66)",
    "ui": "🎨UI (64)",
    "clojure": "☯️Clojure (62)",
    "y combinator": "🟧Y Combinator (61)",
    "photoshop": "🎨Photoshop (59)",
    "lamp": "LAMP (59)",
    "django": "🤠Django (58)",
    "redux": "⚛️Redux (58)",
    "vfx": "VFX (56)",
    "objective c": "🔷Objective C (54)",
    "music": "🔷Music (53)",
    "english teacher": "👨‍🏫English Teacher (53)",
    "fullstack": "🥞Fullstack (52)",
    "legal": "👩‍⚖️Legal (52)",
    "ember": "🐹Ember (51)",
    "serverless": "☁️Serverless (51)",
    "postgresql": "🐬PostgreSQL (51)",
    "net": "🧠Net (50)",
    "hr": "🎯Hr (50)",
    "scrum": "🔁Scrum (49)",
    "cassandra": "🔷Cassandra (49)",
    "travel": "Travel (49)",
    "xamarin": "❎Xamarin (48)",
    "engineering": "🤓Engineering (47)",
    "software": "🤓Software (47)",
    "growth": "🚀Growth (45)",
    "redis": "🧠Redis (45)",
    "c sharp": "🔷C Sharp (44)",
    "illustrator": "Illustrator (42)",
    "fintech": "💰Fintech (41)",
    "perl": "🐪Perl (41)",
    "terraform": "🌳Terraform (41)",
    "kotlin": "☕️Kotlin (40)",
    "product design": "🎨Product Design (39)",
    "shopify": "🛍Shopify (39)",
    "microsoft": "🔷Microsoft (38)",
    "back end": "🍑Back End (37)",
    "accounting": "🔷Accounting (37)",
    "tech": "👨‍🏫Tech (36)",
    "heroku": "🟪Heroku (36)",
    "product management": "📦Product Management (35)",
    "telecom": "🔷Telecom (35)",
    "customer success": "🎧Customer Success (35)",
    "b2b": "💼B2B (34)",
    "amazon": "Amazon (33)",
    "data": "👩‍🔬Data (32)",
    "writing": "✍️Writing (32)",
    "software engineer": "🤓Software Engineer (32)",
    "manager": "💼Manager (31)",
    "content": "✍️Content (31)",
    "automation": "Automation (31)",
    "elixir": "🧪Elixir (30)",
    "analytics": "🔷Analytics (29)",
    "infrastructure": "🌉Infrastructure (29)",
    "apache": "🚁Apache (29)",
    "haskell": "#️⃣Haskell (29)",
    "nginx": "❇️Nginx (28)",
    "symfony": "Symfony (27)",
    "agile": "🐇Agile (27)",
    "web": "💎Web (27)",
    "sre": "Sre (26)",
    "remote": "🏝Remote (26)",
    "support": "🎧Support (26)",
    "microservices": "🔷Microservices (26)",
    "bitcoin": "🏅Bitcoin (25)",
    "lead": "👩‍✈️Lead (25)",
    "ansible": "Ansible (25)",
    "math": "Math (25)",
    "macos": "🍎macOS (25)",
    "work from home": "Work from Home (24)",
    "kafka": "🚁Kafka (24)",
    "project management": "🔷Project Management (23)",
    "hadoop": "🧠Hadoop (23)",
    "technical support": "🔷Technical Support (23)",
    "software development": "🤓Software Development (23)",
    "information services": "👩‍🔬Information Services (23)",
    "development": "🤓Development (23)",
    "ethereum": "💎Ethereum (22)",
    "data viz": "👩‍🔬Data Viz (22)",
    "customer service": "🎧Customer Service (22)",
    "firebase": "🔥Firebase (22)",
    "management": "Management (21)",
    "content marketing": "✍️Content Marketing (21)",
    "security": "🔑Security (21)",
    "gcp": "☁️GCP (21)",
    "lisp": "Lisp (20)",
    "flutter": "🦩Flutter (20)",
    "azure": "☁️Azure (20)",
    "open source": "🧩Open Source (20)",
    "healthcare": "💉Healthcare (20)",
    "software engineering": "🤓Software Engineering (19)",
    "robotics": "🔷Robotics (19)",
    "architect": "📦Architect (19)",
    "node js": "🔗Node JavaScript (18)",
    "jira": "🔷Jira (18)",
    "community": "🔷Community (18)",
    "html5": "🔡HTML5 (18)",
    "account management": "🔷Account Management (18)",
    "solidity": "⛓Solidity (17)",
    "unity": "Unity (17)",
    "operations": "Operations (17)",
    "virtual reality": "Virtual Reality (17)",
    "data entry": "👩‍🔬Data Entry (17)",
    "nosql": "🐬NoSQL (17)",
    "health tech": "🚑Health Tech (16)",
    "english": "English (16)",
    "ai": "🤖AI (16)",
    "spring": "Spring (16)",
    "bootstrap": "🟪Bootstrap (16)",
    "airflow": "🤖Airflow (15)",
    "contracting": "📋Contracting (15)",
    "phonegap": "Phonegap (15)",
    "spark": "Spark (15)",
    "edtech": "👨‍🏫Edtech (15)",
    "digital marketing": "🚥Digital Marketing (15)",
    "outdoors": "Outdoors (14)",
    "business development": "💼Business Development (14)",
    "celery": "🔷Celery (14)",
    "flask": "🍼Flask (14)",
    "rest": "Rest (14)",
    "apollo": "Apollo (14)",
    "erlang": "🟥Erlang (14)",
    "hardware": "Hardware (14)",
    "ror": "Ror (14)",
    "figma": "🎨Figma (14)",
    "research": "👩‍🔬Research (14)",
    "chef": "🔷Chef (13)",
    "crm": "🔷Crm (13)",
    "es6": "Es6 (13)",
    "ci cd": "♾️Ci Cd (13)",
    "apis": "🤖Apis (13)",
    "speech": "🔷Speech (12)",
    "rust": "🦀Rust (12)",
    "clojurescript": "☯️Clojurescript (12)",
    "google cloud platform": "☁️Google Cloud Platform (12)",
    "woocommerce": "🔷Woocommerce (12)",
    "tech support": "🔷Tech Support (12)",
    "leadership": "👩‍✈️Leadership (12)",
    "cycling": "🔷Cycling (12)",
    "it": "🔬IT (11)",
    "product designer": "📦Product Designer (11)",
    "jenkins": "🎩Jenkins (11)",
    "controller": "🔷Controller (11)",
    "test automation": "🧪Test Automation (11)",
    "sysadmin": "♾️Sysadmin (11)",
    "rest api": "🤖Rest API (11)",
    "product development": "🤓Product Development (11)",
    "artificial intelligence": "♾️Artificial Intelligence (11)",
    "rabbitmq": "Rabbitmq (11)",
    "digital": "🏝Digital (11)",
    "ambassador": "Ambassador (11)",
    "dotnet": ".NET (11)",
    "coldfusion": "🔷Coldfusion (11)",
    "email marketing": "🤖Email Marketing (10)",
    "web development": "🤓Web Development (10)",
    "freelance": "🔷Freelance (10)",
    "sketch": "🎨Sketch (10)",
    "tailwind": "💨Tailwind (10)",
    "k8s": "🦑Kubernetes (10)",
    "other": "❓Other (10)",
    "nextjs": "☕️Nextjs (10)",
    "net core": "🔷Net Core (10)",
    "product marketing": "🚥Product Marketing (10)",
    "google cloud": "☁️Google Cloud (10)",
    "scss": "🎨Scss (10)",
    "css3": "🎨Css3 (10)",
    "smart contracts": "📋Smart Contracts (10)",
    "visual basic": "🔷Visual Basic (10)",
    "smart contract": "📋Smart Contract (10)",
    "content creation": "🔷Content Creation (9)",
    "ui design": "🎨UI Design (9)",
    "monitoring": "Monitoring (9)",
    "data engineering": "👩‍🔬Data Engineering (9)",
    "esports": "Esports (9)",
    "adult": "🌶Adult (9)",
    "unix": "Unix (9)",
    "technical": "🔷Technical (9)",
    "ux design": "🎨UX Design (9)",
    "express": "🧩Express (9)",
    "magento": "🔸Magento (9)",
    "grafana": "Grafana (9)",
    "containers": "🤖Containers (9)",
    "etl": "Etl (9)",
    "database": "🧠Database (9)",
    "continuous integration": "🔷Continuous Integration (9)",
    "cypress": "🔷Cypress (9)",
    "e commerce": "🔷E Commerce (9)",
    "gaming": "Gaming (9)",
    "copywriter": "🔷Copywriter (9)",
    "distributed systems": "Distributed Systems (9)",
    "enterprise": "Enterprise (9)",
    "github": "📦Github (8)",
    "community management": "🔷Community Management (8)",
    "project manager": "💼Project Manager (8)",
    "brand": "Brand (8)",
    "web design": "🎨Web Design (8)",
    "team lead": "👩‍✈️Team Lead (8)",
    "programming": "🤓Programming (8)",
    "recruitment": "🎯Recruitment (8)",
    "windows": "Windows (8)",
    "media": "✍️Media (8)",
    "communication": "🔷Communication (8)",
    "professional services": "🔷Professional Services (8)",
    "functional programming": "🤓Functional Programming (8)",
    "mobile development": "🤓Mobile Development (8)",
    "chat": "🔷Chat (8)",
    "voip": "Voip (8)",
    "lambda": "Lambda (8)",
    "node dev": "🔗Node Developer (8)",
    "strategy": "Strategy (8)",
    "user research": "👩‍🔬User Research (8)",
    "zendesk": "🎧Zendesk (7)",
    "technical writing": "🔷Technical Writing (7)",
    "helpdesk": "🎧Helpdesk (7)",
    "cro": "🔷Cro (7)",
    "erp": "Erp (7)",
    "prometheus": "Prometheus (7)",
    "executive": "💼Executive (7)",
    "cryptocurrency": "🏅Cryptocurrency (7)",
    "matlab": "👩‍🔬Matlab (7)",
    "civictech": "♾️Civictech (7)",
    "editing": "Editing (7)",
    "ui ux": "🎨UI UX (7)",
    "ml": "🧠Ml (7)",
    "privacy": "🔷Privacy (7)",
    "snowflake": "Snowflake (7)",
    "agency": "🔷Agency (7)",
    "ionic": "🔷Ionic (7)",
    "recruiting": "🎨Recruiting (7)",
    "affiliate": "Affiliate (7)",
    "start up": "Start Up (7)",
    "advertising": "🔥Advertising (7)",
    "business": "💼Business (7)",
    "amazon web services": "🔷Amazon Web Services (7)",
    "data analysis": "👩‍🔬Data Analysis (7)",
    "selenium": "Selenium (7)",
    "phoenix": "🐓Phoenix (7)",
    "go": "🐀Go (6)",
    "frontend development": "🎨Frontend Development (6)",
    "contract": "📋Contract (6)",
    "remote work": "🏝Remote Work (6)",
    "account manager": "💼Account Manager (6)",
    "full stack developer": "🤓Full Stack Developer (6)",
    "oop": "🧠Oop (6)",
    "german": "German (6)",
    "chief": "🔷Chief (6)",
    "branding": "Branding (6)",
    "biotech": "📡Biotech (6)",
    "zf2": "Zf2 (6)",
    "marketing manager": "🚥Marketing Manager (6)",
    "cto": "🔷Cto (6)",
    "openstack": "🔷Openstack (6)",
    "redshift": "Redshift (6)",
    "algorithms": "👩‍🔬Algorithms (6)",
    "ci": "♾️Ci (6)",
    "english teaching": "👨‍🏫English Teaching (6)",
    "sdk": "Sdk (6)",
    "app": "🍎App (6)",
    "people": "People (6)",
    "writer": "Writer (6)",
    "data analyst": "👩‍🔬Data Analyst (6)",
    "grpc": "🔷Grpc (6)",
    "react js": "☕️React JavaScript (6)",
    "gitlab": "👩‍🔬Gitlab (6)",
    "rxjs": "☕️Rxjs (6)",
    "vuejs": "☕️Vuejs (6)",
    "nestjs": "☕️Nestjs (6)",
    "software testing": "🧪Software Testing (6)",
    "mariadb": "Mariadb (6)",
    "webmaster": "Webmaster (6)",
    "product owner": "📦Product Owner (6)",
    "ux ui": "🎨UX UI (6)",
    "demand generation": "Demand Generation (6)",
    "quality": "🔬Quality (6)",
    "site reliability": "Site Reliability (6)",
    "email": "🤖Email (6)",
    "manual testing": "🧪Manual Testing (6)",
    "reactnative": "⚛️Reactnative (6)",
    "next": "Next (6)",
    "user acquisition": "🎨User Acquisition (6)",
    "nuxt": "🎨Nuxt (6)",
    "publishing": "Publishing (6)",
    "bash": "Bash (6)",
    "pandas": "Pandas (6)",
    "electron": "⚛️Electron (5)",
    "argocd": "♾️Argocd (5)",
    "cloudformation": "☁️Cloudformation (5)",
    "pytest": "🧪Pytest (5)",
    "html css": "🔡HTML CSS (5)",
    "growth hacker": "🚀Growth Hacker (5)",
    "cd": "♾️Cd (5)",
    "spring boot": "Spring Boot (5)",
    "bigquery": "Bigquery (5)",
    "technology": "🔷Technology (5)",
    "sidekiq": "Sidekiq (5)",
    "dynamodb": "Dynamodb (5)",
    "partnerships": "Partnerships (5)",
    "full stack engineer": "🤓Full Stack Engineer (5)",
    "groovy": "🍸Groovy (5)",
    "iphone": "iPhone (5)",
    "test": "🧪Test (5)",
    "elk": "Elk (5)",
    "tdd": "Tdd (5)",
    "cicd": "♾️Cicd (5)",
    "software design": "🎨Software Design (5)",
    "social impact": "♾️Social Impact (5)",
    "rest apis": "🤖Rest Apis (5)",
    "non profit": "Non Profit (5)",
    "apps": "Apps (5)",
    "social": "✍️Social (5)",
    "online": "Online (5)",
    "software developer": "🤓Software Developer (5)",
    "community manager": "💼Community Manager (5)",
    "digital media": "📦Digital Media (5)",
    "remote jobs": "🏝Remote Jobs (5)",
    "oracle": "🔷Oracle (5)",
    "account executive": "💼Account Executive (5)",
    "ppc": "🔷Ppc (5)",
    "meteor js": "☕️Meteor JavaScript (5)",
    "customer": "🎧Customer (5)",
    "json": "🧠Json (5)",
    "ruby on rails": "🤖Ruby on Rails (5)",
    "liquid": "🎨Liquid (5)",
    "chatbot": "🔷Chatbot (5)",
    "nlp": "NLP (5)"
}