export default {
    "engineer": "👨‍💻Engineer",
    "senior": "👵Senior",
    "executive": "💼Executive",
    "javascript": "☕️JavaScript",
    "ruby": "💎Ruby",
    "full stack": "🥞Full Stack",
    "devops": "♾️DevOps",
    "front end": "🎨Front End",
    "backend": "🍑Backend",
    "php": "🐘PHP",
    "non tech": "🔌Non Tech",
    "web developer": "🤓Web Developer",
    "ios": "🍎iOS",
    "marketing": "🚥Marketing",
    "design": "🎨Design",
    "c": "🔷C",
    "react": "⚛️React",
    "node": "🔗Node",
    "mobile": "📱Mobile",
    "admin": "♾️Admin",
    "java": "☕️Java",
    "golang": "🐀Golang",
    "python": "🐍Python",
    "sales": "💼Sales",
    "product manager": "📦Product Manager",
    "architecture": "📦Architecture",
    "customer support": "🎧Customer Support",
    "android": "🤖Android",
    "css": "🎨CSS",
    "sys admin": "♾️Sys Admin",
    "c plus plus": "➕C Plus Plus",
    "meteor": "☄️Meteor",
    "html": "🔡HTML",
    "user interface": "🎨User Interface",
    "user experience": "🎨User Experience",
    "js": "☕️JavaScript",
    "cloud": "☁️Cloud",
    "quality assurance": "🔬Quality Assurance",
    "infosec": "🔑InfoSec",
    "full time": "⏰Full Time",
    "angular": "🅰️Angular",
    "testing": "🧪Testing",
    "api": "🤖API",
    "data science": "👩‍🔬Data Science",
    "teaching": "👨‍🏫Teaching",
    "ops": "♾️Ops",
    "sql": "🐬SQL",
    "finance": "💰Finance",
    "wordpress": "✍️Wordpress",
    "analyst": "🤔Analyst",
    "saas": "📦SaaS",
    "education": "👨‍🏫Education",
    "junior": "👶Junior",
    "linux": "🐧Linux",
    "drupal": "💧Drupal",
    "consulting": "💼Consulting",
    "react native": "⚛️React Native",
    "internship": "Internship",
    "aws": "☁️AWS",
    "medical": "🚑Medical",
    "social media": "✍️Social Media",
    "bus dev": "🤓Bus Developer",
    "ecommerce": "🛍Ecommerce",
    "scala": "☕️Scala",
    "jquery": "🧩jQuery",
    "game dev": "🕹Game Developer",
    "machine learning": "🤖Machine Learning",
    "typescript": "🟦Typescript",
    "copywriting": "✍️Copywriting",
    "ads": "📗Ads",
    "stats": "👩‍🔬Stats",
    "seo": "🔎SEO",
    "excel": "📗Excel",
    "rails": "🛤Rails",
    "part time": "⏰Part Time",
    "docker": "🐳Docker",
    "mongo": "🍃Mongo",
    "tech lead": "👩‍✈️Tech Lead",
    "mongodb": "🍃Mongo",
    "web3": "💎Web3",
    "postgres": "🐬Postgres",
    "dot net": "🌊Dot Net",
    "vue": "💚Vue",
    "swift": "🐇Swift",
    "graphql": "⚛️GraphQL",
    "salesforce": "☁️Salesforce",
    "laravel": "📦Laravel",
    "big data": "🧠Big Data",
    "kubernetes": "🦑Kubernetes",
    "elasticsearch": "🧩Elasticsearch",
    "frontend": "🎨Frontend",
    "dba": "🥞Database Admin",
    "virtual assistant": "Virtual Assistant",
    "video": "Video",
    "blockchain": "⛓Blockchain",
    "recruiter": "🎯Recruiter",
    "developer": "🤓Developer",
    "mysql": "🐬MySQL",
    "qa": "🕵️Quality Assurance",
    "product": "📦Product",
    "crypto": "🏅Crypto",
    "git": "📦Git",
    "ux": "🎨UX",
    "startup": "🚀Startup",
    "embedded": "💡Embedded",
    "ui": "🎨UI",
    "clojure": "☯️Clojure",
    "y combinator": "🟧Y Combinator",
    "photoshop": "🎨Photoshop",
    "lamp": "LAMP",
    "django": "🤠Django",
    "redux": "⚛️Redux",
    "vfx": "VFX",
    "objective c": "🔷Objective C",
    "music": "🔷Music",
    "english teacher": "👨‍🏫English Teacher",
    "fullstack": "🥞Fullstack",
    "legal": "👩‍⚖️Legal",
    "ember": "🐹Ember",
    "serverless": "☁️Serverless",
    "postgresql": "🐬PostgreSQL",
    "net": "🧠Net",
    "hr": "🎯Hr",
    "scrum": "🔁Scrum",
    "cassandra": "🔷Cassandra",
    "travel": "Travel",
    "xamarin": "❎Xamarin",
    "engineering": "🤓Engineering",
    "software": "🤓Software",
    "growth": "🚀Growth",
    "redis": "🧠Redis",
    "c sharp": "🔷C Sharp",
    "illustrator": "Illustrator",
    "fintech": "💰Fintech",
    "perl": "🐪Perl",
    "terraform": "🌳Terraform",
    "kotlin": "☕️Kotlin",
    "product design": "🎨Product Design",
    "shopify": "🛍Shopify",
    "microsoft": "🔷Microsoft",
    "back end": "🍑Back End",
    "accounting": "🔷Accounting",
    "tech": "👨‍🏫Tech",
    "heroku": "🟪Heroku",
    "product management": "📦Product Management",
    "telecom": "🔷Telecom",
    "customer success": "🎧Customer Success",
    "b2b": "💼B2B",
    "amazon": "Amazon",
    "data": "👩‍🔬Data",
    "writing": "✍️Writing",
    "software engineer": "🤓Software Engineer",
    "manager": "💼Manager",
    "content": "✍️Content",
    "automation": "Automation",
    "elixir": "🧪Elixir",
    "analytics": "🔷Analytics",
    "infrastructure": "🌉Infrastructure",
    "apache": "🚁Apache",
    "haskell": "#️⃣Haskell",
    "nginx": "❇️Nginx",
    "symfony": "Symfony",
    "agile": "🐇Agile",
    "web": "💎Web",
    "sre": "Sre",
    "remote": "🏝Remote",
    "support": "🎧Support",
    "microservices": "🔷Microservices",
    "bitcoin": "🏅Bitcoin",
    "lead": "👩‍✈️Lead",
    "ansible": "Ansible",
    "math": "Math",
    "macos": "🍎macOS",
    "work from home": "Work from Home",
    "kafka": "🚁Kafka",
    "project management": "🔷Project Management",
    "hadoop": "🧠Hadoop",
    "technical support": "🔷Technical Support",
    "software development": "🤓Software Development",
    "information services": "👩‍🔬Information Services",
    "development": "🤓Development",
    "ethereum": "💎Ethereum",
    "data viz": "👩‍🔬Data Viz",
    "customer service": "🎧Customer Service",
    "firebase": "🔥Firebase",
    "management": "Management",
    "content marketing": "✍️Content Marketing",
    "security": "🔑Security",
    "gcp": "☁️GCP",
    "lisp": "Lisp",
    "flutter": "🦩Flutter",
    "azure": "☁️Azure",
    "open source": "🧩Open Source",
    "healthcare": "💉Healthcare",
    "software engineering": "🤓Software Engineering",
    "robotics": "🔷Robotics",
    "architect": "📦Architect",
    "node js": "🔗Node JavaScript",
    "jira": "🔷Jira",
    "community": "🔷Community",
    "html5": "🔡HTML5",
    "account management": "🔷Account Management",
    "solidity": "⛓Solidity",
    "unity": "Unity",
    "operations": "Operations",
    "virtual reality": "Virtual Reality",
    "data entry": "👩‍🔬Data Entry",
    "nosql": "🐬NoSQL",
    "health tech": "🚑Health Tech",
    "english": "English",
    "ai": "🤖AI",
    "spring": "Spring",
    "bootstrap": "🟪Bootstrap",
    "airflow": "🤖Airflow",
    "contracting": "📋Contracting",
    "phonegap": "Phonegap",
    "spark": "Spark",
    "edtech": "👨‍🏫Edtech",
    "digital marketing": "🚥Digital Marketing",
    "outdoors": "Outdoors",
    "business development": "💼Business Development",
    "celery": "🔷Celery",
    "flask": "🍼Flask",
    "rest": "Rest",
    "apollo": "Apollo",
    "erlang": "🟥Erlang",
    "hardware": "Hardware",
    "ror": "Ror",
    "figma": "🎨Figma",
    "research": "👩‍🔬Research",
    "chef": "🔷Chef",
    "crm": "🔷Crm",
    "es6": "Es6",
    "ci cd": "♾️Ci Cd",
    "apis": "🤖Apis",
    "speech": "🔷Speech",
    "rust": "🦀Rust",
    "clojurescript": "☯️Clojurescript",
    "google cloud platform": "☁️Google Cloud Platform",
    "woocommerce": "🔷Woocommerce",
    "tech support": "🔷Tech Support",
    "leadership": "👩‍✈️Leadership",
    "cycling": "🔷Cycling",
    "it": "🔬IT",
    "product designer": "📦Product Designer",
    "jenkins": "🎩Jenkins",
    "controller": "🔷Controller",
    "test automation": "🧪Test Automation",
    "sysadmin": "♾️Sysadmin",
    "rest api": "🤖Rest API",
    "product development": "🤓Product Development",
    "artificial intelligence": "♾️Artificial Intelligence",
    "rabbitmq": "Rabbitmq",
    "digital": "🏝Digital",
    "ambassador": "Ambassador",
    "dotnet": ".NET",
    "coldfusion": "🔷Coldfusion",
    "email marketing": "🤖Email Marketing",
    "web development": "🤓Web Development",
    "freelance": "🔷Freelance",
    "sketch": "🎨Sketch",
    "tailwind": "💨Tailwind",
    "k8s": "🦑Kubernetes",
    "other": "❓Other",
    "nextjs": "☕️Nextjs",
    "net core": "🔷Net Core",
    "product marketing": "🚥Product Marketing",
    "google cloud": "☁️Google Cloud",
    "scss": "🎨Scss",
    "css3": "🎨Css3",
    "smart contracts": "📋Smart Contracts",
    "visual basic": "🔷Visual Basic",
    "smart contract": "📋Smart Contract",
    "content creation": "🔷Content Creation",
    "ui design": "🎨UI Design",
    "monitoring": "Monitoring",
    "data engineering": "👩‍🔬Data Engineering",
    "esports": "Esports",
    "adult": "🌶Adult",
    "unix": "Unix",
    "technical": "🔷Technical",
    "ux design": "🎨UX Design",
    "express": "🧩Express",
    "magento": "🔸Magento",
    "grafana": "Grafana",
    "containers": "🤖Containers",
    "etl": "Etl",
    "database": "🧠Database",
    "continuous integration": "🔷Continuous Integration",
    "cypress": "🔷Cypress",
    "e commerce": "🔷E Commerce",
    "gaming": "Gaming",
    "copywriter": "🔷Copywriter",
    "distributed systems": "Distributed Systems",
    "enterprise": "Enterprise",
    "github": "📦Github",
    "community management": "🔷Community Management",
    "project manager": "💼Project Manager",
    "brand": "Brand",
    "web design": "🎨Web Design",
    "team lead": "👩‍✈️Team Lead",
    "programming": "🤓Programming",
    "recruitment": "🎯Recruitment",
    "windows": "Windows",
    "media": "✍️Media",
    "communication": "🔷Communication",
    "professional services": "🔷Professional Services",
    "functional programming": "🤓Functional Programming",
    "mobile development": "🤓Mobile Development",
    "chat": "🔷Chat",
    "voip": "Voip",
    "lambda": "Lambda",
    "node dev": "🔗Node Developer",
    "strategy": "Strategy",
    "user research": "👩‍🔬User Research",
    "zendesk": "🎧Zendesk",
    "technical writing": "🔷Technical Writing",
    "helpdesk": "🎧Helpdesk",
    "cro": "🔷Cro",
    "erp": "Erp",
    "prometheus": "Prometheus",
    "cryptocurrency": "🏅Cryptocurrency",
    "matlab": "👩‍🔬Matlab",
    "civictech": "♾️Civictech",
    "editing": "Editing",
    "ui ux": "🎨UI UX",
    "ml": "🧠Ml",
    "privacy": "🔷Privacy",
    "snowflake": "Snowflake",
    "agency": "🔷Agency",
    "ionic": "🔷Ionic",
    "recruiting": "🎨Recruiting",
    "affiliate": "Affiliate",
    "start up": "Start Up",
    "advertising": "🔥Advertising",
    "business": "💼Business",
    "amazon web services": "🔷Amazon Web Services",
    "data analysis": "👩‍🔬Data Analysis",
    "selenium": "Selenium",
    "phoenix": "🐓Phoenix",
    "go": "🐀Go",
    "frontend development": "🎨Frontend Development",
    "contract": "📋Contract",
    "remote work": "🏝Remote Work",
    "account manager": "💼Account Manager",
    "full stack developer": "🤓Full Stack Developer",
    "oop": "🧠Oop",
    "german": "German",
    "chief": "🔷Chief",
    "branding": "Branding",
    "biotech": "📡Biotech",
    "zf2": "Zf2",
    "marketing manager": "🚥Marketing Manager",
    "cto": "🔷Cto",
    "openstack": "🔷Openstack",
    "redshift": "Redshift",
    "algorithms": "👩‍🔬Algorithms",
    "ci": "♾️Ci",
    "english teaching": "👨‍🏫English Teaching",
    "sdk": "Sdk",
    "app": "🍎App",
    "people": "People",
    "writer": "Writer",
    "data analyst": "👩‍🔬Data Analyst",
    "grpc": "🔷Grpc",
    "react js": "☕️React JavaScript",
    "gitlab": "👩‍🔬Gitlab",
    "rxjs": "☕️Rxjs",
    "vuejs": "☕️Vuejs",
    "nestjs": "☕️Nestjs",
    "software testing": "🧪Software Testing",
    "mariadb": "Mariadb",
    "webmaster": "Webmaster",
    "product owner": "📦Product Owner",
    "ux ui": "🎨UX UI",
    "demand generation": "Demand Generation",
    "quality": "🔬Quality",
    "site reliability": "Site Reliability",
    "email": "🤖Email",
    "manual testing": "🧪Manual Testing",
    "reactnative": "⚛️Reactnative",
    "next": "Next",
    "user acquisition": "🎨User Acquisition",
    "nuxt": "🎨Nuxt",
    "publishing": "Publishing",
    "bash": "Bash",
    "pandas": "Pandas",
    "electron": "⚛️Electron",
    "argocd": "♾️Argocd",
    "cloudformation": "☁️Cloudformation",
    "pytest": "🧪Pytest",
    "html css": "🔡HTML CSS",
    "growth hacker": "🚀Growth Hacker",
    "cd": "♾️Cd",
    "spring boot": "Spring Boot",
    "bigquery": "Bigquery",
    "technology": "🔷Technology",
    "sidekiq": "Sidekiq",
    "dynamodb": "Dynamodb",
    "partnerships": "Partnerships",
    "full stack engineer": "🤓Full Stack Engineer",
    "groovy": "🍸Groovy",
    "iphone": "iPhone",
    "test": "🧪Test",
    "elk": "Elk",
    "tdd": "Tdd",
    "cicd": "♾️Cicd",
    "software design": "🎨Software Design",
    "social impact": "♾️Social Impact",
    "rest apis": "🤖Rest Apis",
    "non profit": "Non Profit",
    "apps": "Apps",
    "social": "✍️Social",
    "online": "Online",
    "software developer": "🤓Software Developer",
    "community manager": "💼Community Manager",
    "digital media": "📦Digital Media",
    "remote jobs": "🏝Remote Jobs",
    "oracle": "🔷Oracle",
    "account executive": "💼Account Executive",
    "ppc": "🔷Ppc",
    "meteor js": "☕️Meteor JavaScript",
    "customer": "🎧Customer",
    "json": "🧠Json",
    "ruby on rails": "🤖Ruby on Rails",
    "liquid": "🎨Liquid",
    "chatbot": "🔷Chatbot",
    "nlp": "NLP"
}